### ISSUE TITLE
Package won't appear in MiKTeX Console's Package Manager

### ISSUE THREAD

**Issue by alexvioni** [ho-tex/kvoptions#1]
While compiling a .tex file this package appears to be a requirement and is missing but I cannot find it in the package manager in order to install it. I tried installing it manually, but it still doesn't work. Any ideas? Thank you!

**Comment by u-fischer** [comment]
See https://github.com/MiKTeX/miktex-packaging/issues/145.

**Comment by alexvioni** [comment]
That was it, thanks a lot!
