### ISSUE TITLE
kvoptions should not be in collection-latexextra

### ISSUE THREAD

**Issue by chdiza** [ho-tex/kvoptions#3]
kvoptions, pdftexcmds, and epstopdf-pkg have all bitten me in recent days.

I don't use luatex or anything fancy, but on separate occasions typesetting even simple documents with pdflatex or latex bombs out, with a message saying that one of the above packages can't be found.

I can easily `tlmgr install` them, but in wondering why this didn't happen automatically I found out that some of these, including kvoptions, are part of `collection-latexextra`, a collection I purposely do NOT have installed.  That is why I had to manually install them individually.

I think those three (and possibly more that will be split off) should go in the same texlive collection as `oberdiek` used to be in.  Or at least `latex-recommended`.  That way users will automatically get the split-off versions installed when they do a regular update.

The alternative is that users have to discover they're missing a split-off package the hard way.

Side note re the splitting off of things from oberdiek: why can't I run pdflatex or latex on a simple document, one that doesn't use weird packages, without `pdftexcmds`?  The description for that package indicates it's all about luatex, but I don't use luatex.

**Comment by u-fischer** [comment]
>I think those three (and possibly more that will be split off) should go in the same texlive collection as `oberdiek` used to be in. Or at least `latex-recommended`.

This it the wrong place to ask for this, the collections of texlive should be discussed on the texlive mailing list.

> why can't I run pdflatex or latex on a simple document, one that doesn't use weird packages, without `pdftexcmds`?

pdftexcmds defines also "internal" variants of a lots of primitives, and it does it both for pdftex and luatex, e.g. `\pdf@escapestring`, and hyperref uses internally these names.
