### ISSUE TITLE
kvoptions-patch breaks \usepackage[quiet]{fontenc}

### ISSUE THREAD

**Issue by cjorssen** [ho-tex/kvoptions#5]
With an up to date TeXLive 2020, the following does not compile nicely.

```
\documentclass{article}
\usepackage{kvoptions-patch}
\usepackage[quiet]{fontspec}
\begin{document}
Test
\end{document}
```

**Comment by u-fischer** [comment]
kvoptions-patch is no longer compatible with latex. 

We will make it a no-op if the new latex is detected to avoid that it breaks packages like fontspec using \RequirePackageWithOptions .

**Comment by cjorssen** [comment]
Thanks for the commit and the explanation. I guess there will be similar issues with `xkvltxp` packge (`xkeyval` bundle).

**Comment by u-fischer** [comment]
A new version has been sent to ctan.
