### ISSUE TITLE
Problem with kvoptions-patch

### ISSUE THREAD

**Issue by petiard** [ho-tex/kvoptions#7]
Hello!

If I compile:

\documentclass{book}
%\usepackage{kvoptions-patch}
\usepackage{hyperref}
\begin{document}
Hello world!
\end{document}

I have no warning. But if I compile without the % in front of \usepackage{kvoptions-patch}, I have 2 warnings:

LaTeX Warning: You have requested package `atbegshi',
               but the package provides `atbegshi-ltx'.
LaTeX Warning: You have requested package `atveryend',
               but the package provides `atveryend-ltx'.

I investigate and I think the problem is:
kvoptions-patch is incompatible with recent LaTeX
(in kvoptions.pdf: "Change in version v3.14: kvoptions-patch is not compatible with a LATEX 2020-
10-01 or newer and will abort loading if it detects it!")
OK but the test in kvoptions-patch.sty is:

line 99: \providecommand\IfFormatAtLeastTF{\@ifl@t@r\fmtversion}
line 100: \IfFormatAtLeastTF{2020/10/01}{\PackageWarning{kvoptions-patch}%
line 101: {kvoptions-patch is not compatible with \MessageBreak
line 102: LaTeX \fmtversion\MessageBreak Loading is aborted}{}}{}
line 103: \IfFormatAtLeastTF{2020/10/01}{\endinput}{}

The test fails because \fmtversion of LaTeX is 2020-10-01 and not 2020/10/01
So, the test must be:
line 99: \providecommand\IfFormatAtLeastTF{\@ifl@t@r\fmtversion}
line 100: \IfFormatAtLeastTF{2020-10-01}{\PackageWarning{kvoptions-patch}%
line 101: {kvoptions-patch is not compatible with \MessageBreak
line 102: LaTeX \fmtversion\MessageBreak Loading is aborted}{}}{}
line 103: \IfFormatAtLeastTF{2020-10-01}{\endinput}{}

or the \fmtversion of LaTeX must be changed...

Best regards.

François Pétiard

**Comment by u-fischer** [comment]
The test should be able to handle both date formats (but I should use ISO), and I don't get your warning. Please show your complete log-file. 

Sorry in miktex I get it. I will look, but I don't think that it is related to the test.

**Comment by u-fischer** [comment]
miktex seems not to have updated kvoptions.  The last version is from 2019.

**Comment by petiard** [comment]
OK, sorry for the noise. I wait update of MiKTeX.
Thank you!

**Comment by petiard** [comment]
I have another question.
Without kvoptions-patch, how can I pass UTF8 string as value for a key?
For example:
\usepackage[key=éléphant]{mypackage}

Best regards

**Comment by u-fischer** [comment]
Better report it to miktex. It seems to have missed it. And I have no idea about your key problem, I never implement such keys as package options, I always use `\mypackagesetup{key= éléphant}` for such data.

**Comment by petiard** [comment]
OK, thank you!
